//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weatherStationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stationDataModel
    {
        public int var_id { get; set; }
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public string unit { get; set; }
        public string long_name { get; set; }
        public Nullable<double> AirTemp { get; set; }
        public Nullable<double> GHI { get; set; }
        public Nullable<double> WD { get; set; }
        public Nullable<double> WS { get; set; }
        public string Timestamp { get; set; }
    }
}
