//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weatherStationAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weatherStation
    {
        public int id { get; set; }
        public string ws_name { get; set; }
        public string site { get; set; }
        public string portfolio { get; set; }
        public string state { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
    }
}
